---
- name: install packages for nginx
  apt:
    pkg:
      - nginx
      - certbot
      - python3-certbot-nginx

- name: create directories
  file:
    path: '{{ item }}'
    owner: www-data
    mode: 0755
    state: directory
  loop:
    - '{{ sites_root }}'
    - '{{ sites_log_root }}'

- name: set ssl_ciphers
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s*)ssl_protocols\s'
    backrefs: yes
    line: '\1ssl_protocols TLSv1.2 TLSv1.3;'

- include_tasks: site.yml
  loop: '{{ docker_services|dict2items }}'
  loop_control:
    loop_var: service
  when: service.value.get('expose')

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
    state: reloaded