---
- hosts: nglp_local
  connection: local
  gather_facts: false
  vars:

    deploy_path: 'deploy'
    root_domain: 'nglp-test.localhost'
    ssl_path: 'deploy/ssl/ca'
    ssl_path_relative_to_docker_compose: './ssl/ca'
    kibana_domain: 'kibana.{{ root_domain }}'
    kibana_url: 'https://kibana.{{ root_domain }}/'
    elasticsearch_domain: 'elasticsearch.{{ root_domain }}'
    keycloak_domain: 'keycloak.{{ root_domain }}'
    keycloak_url: 'https://keycloak.{{ root_domain }}/'
    grafana_domain: 'grafana.{{ root_domain }}'
  vars_files:
    - vars.yml
#    - vault.yml
  roles:
    - name: certificates
  tasks:

    - file:
        path: '{{ item }}'
        state: directory
      loop:
        - '{{ deploy_path }}'
        - '{{ deploy_path }}/conf'

    - template:
        src: 'templates/{{ item }}'
        dest: '{{ deploy_path }}/{{ item }}'
      loop:
        - docker-compose.yml
        - conf/elasticsearch.yml
        - conf/kibana.yml

    - community.docker.docker_compose:
        project_src: '{{ deploy_path }}'

#    - community.docker.docker_container_exec:
#        container: nglp_es_1
#        command: bin/elasticsearch-keystore add -f xpack.security.authc.realms.oidc.oidc1.rp.client_secret
#        stdin: very-secret