---
- hosts: nglp_test
  vars:
    local_deploy: no

    root_domain: 'nglp-test.cottagelabs.com'
    ssl_path: '/etc/ssl'
    ssl_path_relative_to_docker_compose: '/etc/ssl'

    kibana_url: 'https://kibana.{{ root_domain }}/'
    keycloak_url: 'https://keycloak.{{ root_domain }}/'
  vars_files:
    - vars.yml
  roles:
    - name: nglp
