---
- hosts: nglp_local
  connection: local
  gather_facts: false
  vars:
    local_deploy: yes

    deploy_path: 'deploy'
    root_domain: 'nglp-test.localhost'
    ssl_path_relative_to_docker_compose: './ssl/ca'

    kibana_frontend_url: 'http://localhost:5601/'
    kibana_internal_url: 'http://kibana:5601/'
    keycloak_frontend_url: 'http://localhost:8080/auth/'
    keycloak_internal_url: 'http://keycloak:8080/auth/'
    janeway_domain: 'localhost:8000'
  vars_files:
    - vars.yml
  roles:
    - name: nglp
