---
- hosts: nglp_test
  vars:
    root_domain: 'nglp-test.cottagelabs.com'
    kibana_domain: 'kibana.{{ root_domain }}'
    kibana_url: 'https://kibana.{{ root_domain }}/'
    elasticsearch_domain: 'elasticsearch.{{ root_domain }}'
    keycloak_domain: 'keycloak.{{ root_domain }}'
    keycloak_url: 'https://keycloak.{{ root_domain }}/'
    grafana_domain: 'grafana.{{ root_domain }}'
  vars_files:
    - vars.yml
#    - vault.yml
  roles:
    - name: firewall
    - name: certificates
    - name: nginx
  tasks:
    - name: Add Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker apt repo
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present
        filename: docker
        update_cache: no
      register: docker_apt_repo

    - name: Update apt if apt repo changed
      command:
        cmd: apt update
      when: docker_apt_repo.changed

    - apt:
        pkg:
          - docker-ce
          - docker-compose
          - python3-docker

    - name: Ensure Docker is running and enabled
      systemd:
        name: docker
        enabled: true
        state: started

    - file:
        path: '{{ item }}'
        state: directory
      loop:
        - '{{ deploy_path }}'
        - '{{ deploy_path }}/conf'

    - template:
        src: 'templates/{{ item }}'
        dest: '{{ deploy_path }}/{{ item }}'
      loop:
        - docker-compose.yml
        - conf/elasticsearch.yml
        - conf/kibana.yml


    - community.docker.docker_compose:
        project_src: '{{ deploy_path }}'

#    - community.docker.docker_container_exec:
#        container: nglp_es_1
#        command: bin/elasticsearch-keystore add -f xpack.security.authc.realms.oidc.oidc1.rp.client_secret
#        stdin: very-secret