---
- name: Stat the file, so we know whether it's already there
  stat:
    path: "{{ secrets_path + '/' + name }}"
  register: secrets_file_stat

- name: Create secret file if not already there
  copy:
    content: "{{ lookup('password', '/dev/null') }}"
    dest: "{{ secrets_path + '/' + name }}"
  when: not secrets_file_stat.stat.exists

- name: Read secret file
  slurp:
    path: "{{ secrets_path + '/' + name }}"
  register: secrets_file_data

- name: Set secret variable
  set_fact:
    "{{ name }}": "{{ secrets_file_data.content|b64decode }}"
