---

- file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ deploy_path }}/ssl'
    - '{{ ssl_path }}'
    - '{{ ssl_path }}/certs'
    - '{{ ssl_path }}/private'

- import_tasks: ca.yml

- file:
    path: '{{ deploy_path }}/ssl'
    state: directory

- include_tasks: key_and_cert.yml
  loop: '{{ docker_services|dict2items }}'
  loop_control:
    loop_var: service
  when: service.value.get('key_and_cert')

- include_tasks: key_and_cert.yml
  vars:
    service:
      key: admin
      value:
