---

- file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ deploy_path }}/certs'

- import_tasks: ca.yml

- include_tasks: certificate.yml
  loop: '{{ certificates|dict2items }}'
  loop_control:
    loop_var: certificate
