version: '2.4'
services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    environment:
      node.name: elasticsearch
      cluster.name: moose_elasticsearch
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
      - {{ ca_cert_path }}:/usr/share/elasticsearch/config/root-ca.pem:Z
      - ./ssl/elasticsearch.pem:/usr/share/elasticsearch/config/node-key.pem:Z
      - ./ssl/elasticsearch.crt:/usr/share/elasticsearch/config/node.pem:Z
    ports:
      - "9200:9200"
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    restart: on-failure

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - keycloak
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml:Z
      - {{ ca_cert_path }}:/usr/share/kibana/config/root-ca.pem:Z
      - ./ssl/kibana.pem:/usr/share/elasticsearch/config/node-key.pem:Z
      - ./ssl/kibana.crt:/usr/share/elasticsearch/config/node.pem:Z

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,natel-plotly-panel,https://github.com/chartwerk/grafana-chartwerk-app/archive/0.3.2.zip;corpglory-chartwerk-panel,https://github.com/gipong/grafana-groupedbarchart-panel/archive/master.zip;grafana-groupedbarchart-panel
    volumes:
      - graf-store:/var/lib/grafana
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    environment:
      - NODE_NAME=elasticsearch
    ports:
      - 9600:9600
    networks:
      - elastic
    depends_on:
      - elasticsearch

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-s" , "-f", "http://localhost:8080/auth/realms/master/.well-known/openid-configuration"]

volumes:
  data:
    driver: local
  graf-store:
    driver: local

networks:
  elastic:
    driver: bridge
